function f = f_BCRFBP(as,ms,mu,th,x,xdot,y,ydot,z,zdot)
%f_BCRFBP
%    F = f_BCRFBP(AS,MS,MU,TH,X,XDOT,Y,YDOT,Z,ZDOT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Oct-2025 20:40:16

t2 = cos(th);
t3 = sin(th);
t4 = mu+x;
t5 = y.^2;
t6 = z.^2;
t9 = 1.0./as.^2;
t10 = mu-1.0;
t7 = as.*t2;
t8 = as.*t3;
t11 = t4-1.0;
t12 = t4.^2;
t13 = t7+x;
t15 = t11.^2;
t18 = (t8-y).^2;
t19 = t5+t6+t12;
t17 = t13.^2;
t20 = t5+t6+t15;
t21 = 1.0./t19.^(3.0./2.0);
t22 = 1.0./t20.^(3.0./2.0);
t24 = t10.*t21;
t25 = t6+t17+t18;
t23 = mu.*t22;
t26 = 1.0./t25.^(3.0./2.0);
f = [xdot;ydot;zdot;x+ydot.*2.0+t4.*t24-t11.*t23+ms.*t2.*t9-ms.*t13.*t26;xdot.*-2.0+y-y.*(t23-t24)-ms.*t3.*t9+ms.*t26.*(t8-y);-z.*(t23-t24+ms.*t26)];
end
