function H_BCRFBP = H_BCRFBP(as,ms,mu,th,x,xdot,y,ydot,z,zdot)
%H_BCRFBP
%    H_BCRFBP = H_BCRFBP(AS,MS,MU,TH,X,XDOT,Y,YDOT,Z,ZDOT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Oct-2025 20:40:20

t2 = cos(th);
t3 = sin(th);
t4 = x+ydot;
t5 = y.^2;
t6 = z.^2;
t7 = -y;
t8 = t7+xdot;
H_BCRFBP = -mu.*1.0./sqrt(t5+t6+(mu+x-1.0).^2)-t4.*x+t8.*y+(mu-1.0).*1.0./sqrt(t5+t6+(mu+x).^2)+t4.^2./2.0+t8.^2./2.0-ms.*1.0./sqrt(t6+(x+as.*t2).^2+(y-as.*t3).^2)+zdot.^2./2.0-1.0./as.^2.*ms.*(t3.*t7+t2.*x);
end
