function H_CRTBP = H_CRTBP(mu,x,y,z)
%H_CRTBP
%    H_CRTBP = H_CRTBP(MU,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Oct-2025 20:40:20

t2 = y.^2;
t3 = z.^2;
H_CRTBP = t2./2.0+mu.*1.0./sqrt(t2+t3+(mu+x-1.0).^2)-(mu-1.0).*1.0./sqrt(t2+t3+(mu+x).^2)+x.^2./2.0;
end
