function J_CRTBP = J_CRTBP(mu,x,xdot,y,ydot,z,zdot)
%J_CRTBP
%    J_CRTBP = J_CRTBP(MU,X,XDOT,Y,YDOT,Z,ZDOT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Oct-2025 20:40:20

t2 = y.^2;
t3 = z.^2;
J_CRTBP = t2+mu.*1.0./sqrt(t2+t3+(mu+x-1.0).^2).*2.0-(mu-1.0).*1.0./sqrt(t2+t3+(mu+x).^2).*2.0+x.^2-xdot.^2-ydot.^2-zdot.^2;
end
